name: My Own Flake8 Test For Python 3.9, 3.10, 3.11

on:
  push:
    # Trigger workflow when a push change is made.

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: action/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: action/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install flake8
        shell: bash
      - name: Testing Flake8
        run: flake8 $(git ls-files '*.py')
        shell: bash
